# Generated by Django 5.2.9 on 2025-12-04 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='enrollment_date',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='date_of_join',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
