# Generated by Django 5.2.9 on 2025-12-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_studentprofile_enrollment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='fee_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
