steps:
  # 1. Build container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-south1-docker.pkg.dev/neural-reactor-480008-v3/coaching-app-repo/coaching-app:$COMMIT_SHA",
        "-t",
        "asia-south1-docker.pkg.dev/neural-reactor-480008-v3/coaching-app-repo/coaching-app:latest",
        "."
      ]

  # 2. Push image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia-south1-docker.pkg.dev/neural-reactor-480008-v3/coaching-app-repo/coaching-app:latest"]

  # 3. Deploy to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "coaching-app",
        "--image",
        "asia-south1-docker.pkg.dev/neural-reactor-480008-v3/coaching-app-repo/coaching-app:latest",
        "--region",
        "asia-south1",
        "--platform",
        "managed",
        "--allow-unauthenticated"
      ]

images:
  - "asia-south1-docker.pkg.dev/neural-reactor-480008-v3/coaching-app-repo/coaching-app:latest"
