steps:
  # 1. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      "build",
      "-t",
      "asia-south1-docker.pkg.dev/$PROJECT_ID/coaching-app-repo/coaching-app:$COMMIT_SHA",
      "-t",
      "asia-south1-docker.pkg.dev/$PROJECT_ID/coaching-app-repo/coaching-app:latest",
      "."
    ]

  # 2. Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      "push",
      "asia-south1-docker.pkg.dev/$PROJECT_ID/coaching-app-repo/coaching-app:latest"
    ]

  # 3. Deploy to Cloud Run with variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      "run",
      "deploy",
      "coaching-app",
      "--image=asia-south1-docker.pkg.dev/$PROJECT_ID/coaching-app-repo/coaching-app:latest",
      "--region=asia-south1",
      "--platform=managed",
      "--allow-unauthenticated",
      "--set-env-vars",
      "SECRET_KEY=$(_SECRET_KEY),DATABASE_URL=$(_DATABASE_URL),GS_BUCKET_NAME=$(_GS_BUCKET_NAME),ALLOWED_HOSTS=$(_ALLOWED_HOSTS)"
    ]

images:
  - "asia-south1-docker.pkg.dev/$PROJECT_ID/coaching-app-repo/coaching-app:latest"
