steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "--no-cache",
        "-t",
        "us-central1-docker.pkg.dev/neural-reactor-480008-v3/cloud-run-source-deploy/shoebsiracademy:$BUILD_ID",
        "."
      ]

  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/neural-reactor-480008-v3/cloud-run-source-deploy/shoebsiracademy:$BUILD_ID"
      ]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "shoebsiracademy",
        "--image",
        "us-central1-docker.pkg.dev/neural-reactor-480008-v3/cloud-run-source-deploy/shoebsiracademy:$BUILD_ID",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--revision-suffix",
        "$BUILD_ID"
      ]

images:
  - "us-central1-docker.pkg.dev/neural-reactor-480008-v3/cloud-run-source-deploy/shoebsiracademy:$BUILD_ID"
