steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/django-app:$COMMIT_SHA', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/django-app:latest', '.']

  # 2. Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/django-app']

  # 3. Apply Migrations (Optional - better to run as a separate Job, but this works for simple cases)
  # Note: This requires the Cloud Build service account to have Cloud SQL Client role and access to secrets
  # - name: 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/django-app:latest'
  #   entrypoint: 'python'
  #   args: ['manage.py', 'migrate']
  #   env:
  #     - 'DATABASE_URL=$$_DATABASE_URL'
  #     - 'SECRET_KEY=$$_SECRET_KEY'
  #   secretEnv: ['DATABASE_URL', 'SECRET_KEY']

  # 4. Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'django-app'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/django-app:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      # Ensure you set these secrets in Cloud Build triggers or Secret Manager
      # - '--set-secrets=DATABASE_URL=DATABASE_URL:latest,SECRET_KEY=SECRET_KEY:latest'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/django-app:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/django-app:latest'

# Available secrets (configure in Cloud Build settings)
# availableSecrets:
#   secretManager:
#   - versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
#     env: 'DATABASE_URL'
#   - versionName: projects/$PROJECT_ID/secrets/SECRET_KEY/versions/latest
#     env: 'SECRET_KEY'
