# Generated by Django 5.2.9 on 2025-12-19 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcmtoken',
            options={'verbose_name': 'FCM Token', 'verbose_name_plural': 'FCM Tokens'},
        ),
        migrations.AddField(
            model_name='fcmtoken',
            name='browser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fcmtoken',
            name='device_type',
            field=models.CharField(choices=[('WEB', 'Web Browser'), ('MOBILE', 'Mobile App')], default='WEB', max_length=10),
        ),
        migrations.AddField(
            model_name='fcmtoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fcmtoken',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='fcmtoken',
            index=models.Index(fields=['user', 'is_active'], name='notificatio_user_id_a26597_idx'),
        ),
        migrations.AddIndex(
            model_name='fcmtoken',
            index=models.Index(fields=['token'], name='notificatio_token_23c95b_idx'),
        ),
    ]
